<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Card {

  static $swaggerTypes = array(
      'name_on_card' => 'string',
      'card_type' => 'string',
      'expiration_year' => 'string',
      'card_id' => 'int',
      'expiration_month' => 'string',
      'nickname' => 'string',
      'last_4_digits' => 'string'

    );

  /**
  * Name on card
  */
  public $name_on_card; // string
  /**
  * Card type
  */
  public $card_type; // string
  /**
  * Year of card expiration date (4 digits)
  */
  public $expiration_year; // string
  /**
  * SubtleData Card ID
  */
  public $card_id; // int
  /**
  * Month of card expiration date (2 digits)
  */
  public $expiration_month; // string
  /**
  * Card nickname
  */
  public $nickname; // string
  /**
  * Last 4 digits on card
  */
  public $last_4_digits; // string
  }

