<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CardPayment {

  static $swaggerTypes = array(
      'name_on_card' => 'string',
      'tip_amount' => 'float',
      'expiration_year' => 'string',
      'amount_before_tip' => 'float',
      'tip_type' => 'int',
      'card_id' => 'int',
      'expiration_month' => 'string',
      'mag_track_2' => 'string',
      'mag_track_1' => 'string',
      'signature_image' => 'string',
      'tender_type_id' => 'int',
      'billing_zip' => 'string',
      'card_number' => 'string'

    );

  /**
  * Name on card
  */
  public $name_on_card; // string
  /**
  * Payment Tip Amount
  */
  public $tip_amount; // float
  /**
  * Expration Year
  */
  public $expiration_year; // string
  /**
  * Payment Amount Before Tip
  */
  public $amount_before_tip; // float
  /**
  * Pass tip ID or use 0 to specify tip
  */
  public $tip_type; // int
  /**
  * SubtleData Credit or Gift Card ID
  */
  public $card_id; // int
  /**
  * Expration Month
  */
  public $expiration_month; // string
  /**
  * Mag Track 2 Data
  */
  public $mag_track_2; // string
  /**
  * Mag Track 1 Data
  */
  public $mag_track_1; // string
  /**
  * Signature Image in Base64
  */
  public $signature_image; // string
  /**
  * tender_type_id
  */
  public $tender_type_id; // int
  /**
  * Billing Zip Code
  */
  public $billing_zip; // string
  /**
  * CC Number
  */
  public $card_number; // string
  }

