<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Employee {

  static $swaggerTypes = array(
      'ssn' => 'string',
      'last_name' => 'string',
      'middle_name' => 'string',
      'emergency_contact_number' => 'string',
      'date_terminated' => 'string',
      'dob' => 'string',
      'alcohol_commission_number' => 'string',
      'alcohol_commission_expiration_date' => 'string',
      'first_name' => 'string',
      'is_manager' => 'bool',
      'health_cert_number' => 'string',
      'mobile_phone' => 'string',
      'date_hired' => 'string',
      'home_phone' => 'string',
      'country_of_nationality' => 'string',
      'emergency_contact_name' => 'string',
      'health_cert_expiration_date' => 'string',
      'date_last_review' => 'string',
      'user_name' => 'string',
      'email' => 'string',
      'employee_id' => 'int'

    );

  /**
  * Social Security Number
  */
  public $ssn; // string
  /**
  * Last Name
  */
  public $last_name; // string
  /**
  * Middle Name
  */
  public $middle_name; // string
  /**
  * Emergency Contact Number
  */
  public $emergency_contact_number; // string
  /**
  * Date of Termination
  */
  public $date_terminated; // string
  /**
  * Date of Birth
  */
  public $dob; // string
  /**
  * Alcohol Commission Certification Number
  */
  public $alcohol_commission_number; // string
  /**
  * Alcohol Commission Certification Expiration Date
  */
  public $alcohol_commission_expiration_date; // string
  /**
  * First Name
  */
  public $first_name; // string
  /**
  * Manager Flag
  */
  public $is_manager; // bool
  /**
  * Board of Health Certification Number
  */
  public $health_cert_number; // string
  /**
  * Mobile Phone Number
  */
  public $mobile_phone; // string
  /**
  * Hire Date
  */
  public $date_hired; // string
  /**
  * Home Phone Number
  */
  public $home_phone; // string
  /**
  * Country of Nationality
  */
  public $country_of_nationality; // string
  /**
  * Emergency Contact Name
  */
  public $emergency_contact_name; // string
  /**
  * Board of Health Certification Expiration Date
  */
  public $health_cert_expiration_date; // string
  /**
  * Last Review Date
  */
  public $date_last_review; // string
  /**
  * Employee User Name
  */
  public $user_name; // string
  /**
  * Email Address
  */
  public $email; // string
  /**
  * Employee ID
  */
  public $employee_id; // int
  }

