<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ItemToAdd {

  static $swaggerTypes = array(
      'item_id' => 'int',
      'instructions' => 'string',
      'modifiers' => 'array[Modifier]',
      'quantity' => 'int'

    );

  /**
  * Item ID to order
  */
  public $item_id; // int
  /**
  * Additional Order Instructions
  */
  public $instructions; // string
  public $modifiers; // array[Modifier]
  /**
  * Item Quantity
  */
  public $quantity; // int
  }

