<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MenuItem {

  static $swaggerTypes = array(
      'sku' => 'string',
      'food_flag' => 'bool',
      'alcohol_flag' => 'bool',
      'display_name' => 'string',
      'name' => 'string',
      'merchandise_flag' => 'bool',
      'available_for_order' => 'bool',
      'price' => 'float',
      'local_modifier_categories' => 'array[LocalModifierCategorie]',
      'UPC' => 'string',
      'mapped_modifier_categories' => 'array[MappedModifierCategorie]',
      'item_images' => 'array[ItemImage]',
      'cost' => 'float',
      'revenue_center_id' => 'int',
      'description' => 'string',
      'item_id' => 'int',
      'local_pos_id' => 'int',
      'out_of_stock_flag' => 'bool'

    );

  /**
  * Item SKU
  */
  public $sku; // string
  /**
  * Food Flag
  */
  public $food_flag; // bool
  /**
  * Alcohol Flag
  */
  public $alcohol_flag; // bool
  /**
  * Item Display Name
  */
  public $display_name; // string
  /**
  * Item Name
  */
  public $name; // string
  /**
  * Merchandise Flag
  */
  public $merchandise_flag; // bool
  /**
  * Available For Order Flag
  */
  public $available_for_order; // bool
  /**
  * Item Price
  */
  public $price; // float
  public $local_modifier_categories; // array[LocalModifierCategorie]
  /**
  * Item UPC
  */
  public $UPC; // string
  public $mapped_modifier_categories; // array[MappedModifierCategorie]
  public $item_images; // array[ItemImage]
  /**
  * Item Cost Basis
  */
  public $cost; // float
  /**
  * Revenue Center ID
  */
  public $revenue_center_id; // int
  /**
  * Item Description
  */
  public $description; // string
  /**
  * Item ID
  */
  public $item_id; // int
  /**
  * Item POS ID
  */
  public $local_pos_id; // int
  /**
  * Out of Stock
  */
  public $out_of_stock_flag; // bool
  }

