<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class NewExternalPayment {

  static $swaggerTypes = array(
      'payment_source_name' => 'string',
      'tip_amount' => 'float',
      'payment_response_tracking_2' => 'string',
      'payment_response_tracking_3' => 'string',
      'payment_response_tracking_1' => 'string',
      'payment_response_tracking_4' => 'string',
      'amount_before_tip' => 'float',
      'tender_type_id' => 'int',
      'user_id' => 'int',
      'device_id' => 'int'

    );

  /**
  * 
  */
  public $payment_source_name; // string
  /**
  * 
  */
  public $tip_amount; // float
  /**
  * 
  */
  public $payment_response_tracking_2; // string
  /**
  * 
  */
  public $payment_response_tracking_3; // string
  /**
  * 
  */
  public $payment_response_tracking_1; // string
  /**
  * 
  */
  public $payment_response_tracking_4; // string
  /**
  * 
  */
  public $amount_before_tip; // float
  /**
  * 
  */
  public $tender_type_id; // int
  /**
  * 
  */
  public $user_id; // int
  /**
  * 
  */
  public $device_id; // int
  }

