<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class NewPayment {

  static $swaggerTypes = array(
      'tip_amount' => 'float',
      'tip_type' => 'int',
      'testing' => 'bool',
      'card_cvv' => 'string',
      'card_id' => 'int',
      'amount_before_tip' => 'float',
      'user_id' => 'int'

    );

  /**
  * 
  */
  public $tip_amount; // float
  /**
  * 
  */
  public $tip_type; // int
  /**
  * 
  */
  public $testing; // bool
  /**
  * 
  */
  public $card_cvv; // string
  /**
  * 
  */
  public $card_id; // int
  /**
  * 
  */
  public $amount_before_tip; // float
  /**
  * 
  */
  public $user_id; // int
  }

