<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Payment {

  static $swaggerTypes = array(
      'payment_id' => 'int',
      'card_type' => 'string',
      'tip_amount' => 'float',
      'total_amount' => 'float',
      'expiration_year' => 'string',
      'card_nickname' => 'string',
      'name_on_tender' => 'string',
      'expiration_month' => 'string',
      'amount_before_tip' => 'float',
      'credit_card_id' => 'int',
      'last_4_digits' => 'string'

    );

  /**
  * SubtleData Payment ID
  */
  public $payment_id; // int
  /**
  * Credit Card Type
  */
  public $card_type; // string
  /**
  * Payment tip amount
  */
  public $tip_amount; // float
  /**
  * Payment Total Amount
  */
  public $total_amount; // float
  /**
  * Card Expiration Year
  */
  public $expiration_year; // string
  /**
  * Credit Card Nickname
  */
  public $card_nickname; // string
  /**
  * Name on the tender
  */
  public $name_on_tender; // string
  /**
  * Card Expiration Month
  */
  public $expiration_month; // string
  /**
  * Payment amount before tip
  */
  public $amount_before_tip; // float
  /**
  * SubtleData Credit Card ID
  */
  public $credit_card_id; // int
  /**
  * Last 4 card digits
  */
  public $last_4_digits; // string
  }

