<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Tab {

  static $swaggerTypes = array(
      'payment_id' => 'int',
      'name_on_card' => 'string',
      'card_type' => 'string',
      'expiration_year' => 'string',
      'card_nickname' => 'string',
      'card_id' => 'int',
      'expiration_month' => 'string',
      'pos_ticket_id' => 'int',
      'table_id' => 'int',
      'ticket_id' => 'int',
      'table_name' => 'string',
      'pre_auth_amount' => 'float',
      'last_4_digits' => 'string'

    );

  /**
  * SubtleData Payment ID
  */
  public $payment_id; // int
  /**
  * Name on Credit Card
  */
  public $name_on_card; // string
  /**
  * Credit Card Type
  */
  public $card_type; // string
  /**
  * Expiration Year
  */
  public $expiration_year; // string
  /**
  * Credit Card Nickname
  */
  public $card_nickname; // string
  /**
  * SubtleData Credit Card ID
  */
  public $card_id; // int
  /**
  * Expiration Month
  */
  public $expiration_month; // string
  /**
  * POS System Ticket Identifier
  */
  public $pos_ticket_id; // int
  /**
  * Table ID
  */
  public $table_id; // int
  /**
  * Ticket ID
  */
  public $ticket_id; // int
  /**
  * Table Name
  */
  public $table_name; // string
  /**
  * Pre Auth Amount
  */
  public $pre_auth_amount; // float
  /**
  * Last 4 Digits on Card
  */
  public $last_4_digits; // string
  }

