<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Ticket {

  static $swaggerTypes = array(
      'date_closed' => 'string',
      'tax' => 'float',
      'date_opened' => 'string',
      'total' => 'float',
      'location_id' => 'int',
      'employee_id' => 'int',
      'ticket_open' => 'bool',
      'pre_auth_payments' => 'array[PreAuthPayment]',
      'remaining_balance' => 'float',
      'ticket_id' => 'int',
      'table_name' => 'string',
      'revenue_center_id' => 'int',
      'user_id' => 'int',
      'pre_auth_cards' => 'array[PreAuthCard]',
      'discount' => 'float',
      'external_payments' => 'array[ExternalPayment]',
      'cover_count' => 'int',
      'subtotal' => 'float',
      'service_charge' => 'float',
      'date_modified' => 'string',
      'items' => 'array[Item]',
      'pos_ticket_id' => 'int',
      'table_id' => 'int',
      'payments' => 'array[Payment]',
      'connected_users' => 'array[ConnectedUser]'

    );

  /**
  * Date Closed (UTC)
  */
  public $date_closed; // string
  /**
  * Tax amount
  */
  public $tax; // float
  /**
  * Date Opened (UTC)
  */
  public $date_opened; // string
  /**
  * Total amount
  */
  public $total; // float
  /**
  * Location ID
  */
  public $location_id; // int
  /**
  * Employee ID
  */
  public $employee_id; // int
  /**
  * Ticket open/closed status
  */
  public $ticket_open; // bool
  public $pre_auth_payments; // array[PreAuthPayment]
  /**
  * Ticket remaining balance
  */
  public $remaining_balance; // float
  /**
  * Ticket ID
  */
  public $ticket_id; // int
  /**
  * Table Name
  */
  public $table_name; // string
  /**
  * Revenue Center ID
  */
  public $revenue_center_id; // int
  /**
  * User ID
  */
  public $user_id; // int
  public $pre_auth_cards; // array[PreAuthCard]
  /**
  * Discount amount
  */
  public $discount; // float
  public $external_payments; // array[ExternalPayment]
  /**
  * Cover Count
  */
  public $cover_count; // int
  /**
  * Subtotal amount
  */
  public $subtotal; // float
  /**
  * Service charge
  */
  public $service_charge; // float
  /**
  * Date Modified (UTC)
  */
  public $date_modified; // string
  public $items; // array[Item]
  /**
  * POS System Ticket Identifier
  */
  public $pos_ticket_id; // int
  /**
  * Table ID
  */
  public $table_id; // int
  public $payments; // array[Payment]
  public $connected_users; // array[ConnectedUser]
  }

