<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class User {

  static $swaggerTypes = array(
      'first_name' => 'string',
      'last_name' => 'string',
      'user_id' => 'int',
      'last_known_lon' => 'float',
      'email_address' => 'string',
      'dob' => 'string',
      'last_known_lat' => 'float',
      'middle_name' => 'string',
      'cell_phone' => 'string',
      'user_name' => 'string'

    );

  /**
  * First Name
  */
  public $first_name; // string
  /**
  * Last Name
  */
  public $last_name; // string
  /**
  * User ID
  */
  public $user_id; // int
  /**
  * Last Known Longitude
  */
  public $last_known_lon; // float
  /**
  * Email Address
  */
  public $email_address; // string
  /**
  * Date of Birth
  */
  public $dob; // string
  /**
  * Last Known Latitude
  */
  public $last_known_lat; // float
  /**
  * Middle Name
  */
  public $middle_name; // string
  /**
  * Cell Phone
  */
  public $cell_phone; // string
  /**
  * User Name
  */
  public $user_name; // string
  }

