<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class ConcessionsApi {

	function __construct($apiClient) {
	  $this->apiClient = $apiClient;
	}

  /**
	 * createConcessionOrder
	 * Create a concession style order
   * location_id, int: SubtleData Location ID (required)
   * api_key, string: Subtledata API Key (required)
   * body, ConcessionTicketDetails: Concession Ticket Details (required)
   * @return ConcessionOrderResults
	 */

   public function createConcessionOrder($location_id, $api_key, $body) {

  		//parse inputs
  		$resourcePath = "/concessions/{location_id}/order";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "POST";
      $queryParams = array();
      $headerParams = array();

      if($api_key != null) {
  		  $queryParams['api_key'] = $this->apiClient->toQueryValue($api_key);
  		}
  		if($location_id != null) {
  			$resourcePath = str_replace("{" . "location_id" . "}",
  			                            $this->apiClient->toPathValue($location_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'ConcessionOrderResults');
  		return $responseObject;

      }
  
}

